version: 2
jobs:
  build:
    docker:
      - image: node:8.11.3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Update/Install Node PAckages
          command: yarn install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      # Run tests
      - run:
          name: Run Unit Tests
          command: yarn test