version: 2
jobs:
  build:
    docker:
      - image: node:8.11.3

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
        keys:
          - v1-dependeincies-{{ checksum "package.json" }}
          # Fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
        - name: Update/Install Node PAckages
        - command: yarn install

      - save_cache:
        paths:
          - node_modules
        keys: v1-dependencies-{{ checksum "package.json" }}

      # Run tests
      - run:
        - name: Run Unit Tests
        - command: yarn test