version: 2
jobs:
  build:
    docker:
      - image: node:8.11.3
      - image: circleci/postgres
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: cd_test_db

    working_directory: ~/repo

    environment:
      APP_NAME: Coders Dictionary
      APP_VERSION: 0.0.0
      APP_URL: http://localhost:3050
      APP_PORT: 3050
      APP_DEBUG: true
      APP_KEY: U2FsdGVkX1/KOxGLPzJDw8X/UYtdrpg7MGHAOyrhv42NsI33Yi9rdfjWDC6r9crTkp3qu/GElyC28wXWPoYO2w==
      DB_NAME: cd_test_db
      DB_USER: root
      DB_PASSWORD: ''
      DB_HOST: localhost
      DB_DIALECT: postgres
      DB_LOGGING: false

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Update/Install Node PAckages
          command: yarn install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      # Run tests
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run Test and Coverage
          command: |
            ./cc-test-reporter before-build
            yarn tac
            ./cc-test-reporter after-build --exit-code $?